### ISSUE TITLE
Is there a dump of the raw json files / or an index of the files

### ISSUE THREAD

**Issue by emilienschultz** [polomarcus/television-news-analyser#17]
Since each json file has a different hash this is not easy to dl : either a list of the files / a yearly json would be useful.

**Comment by polomarcus** [comment]
@emilienschultz, i guess the problem is to read folders with Pandas and python ?

David from ClimatMedias has done it this way, it may solve your problem :crossed_fingers: 
* https://github.com/polomarcus/television-news-analyser/blob/main/notebooks/01.%20Last%20week%20topics.ipynb

**Comment by emilienschultz** [comment]
More than requesting the github to avoid to dl the whole repository. But yes, I used this solution for the moment.

**Comment by polomarcus** [comment]
Done this way 

https://github.com/polomarcus/television-news-analyser/pull/18
