### ISSUE TITLE
feature: add simpler data

### ISSUE THREAD

**Issue by SylvainBreton** [polomarcus/television-news-analyser#29]
Would it be possible to add somewhere on the repo some sample data more accessible. For example a csv that store the number of title per day.

I am looking for those data (to do a plot of the number of articles as a function of the daily temperature for education purpose). I actually can install the repo and perform sql request (providing some time) but it is not the case of many people interested in those data (teachers, journalists...).

Maybe it is a design choice, if so you can close this issue.

**Comment by polomarcus** [comment]
Hi @SylvainBreton 

Tell me if this match your needs, it's still in JSON but it may work : 
* https://github.com/polomarcus/television-news-analyser/blob/main/docs/data-aggregated-news-json/agg.json/agg.json

All the files inside [this folder](https://github.com/polomarcus/television-news-analyser/blob/main/docs/data-aggregated-news-json/) provide the data for this website directly : https://observatoire.climatmedias.org/

--- 
I've just added some [TSV data](https://github.com/polomarcus/television-news-analyser#data-sinks) partionned by year only :
> CSV or actually Tab Separated Values (TSV) compressed ([if you don't know how to uncompressed these data](https://www.wikihow.com/Extract-a-Gz-File)) ➡️️ https://github.com/polomarcus/television-news-analyser/tree/main/data-news-csv/

**Comment by SylvainBreton** [comment]
Yeah, this is totally fit my needs.
Thank you
